### ISSUE TITLE
Encrypted contents always change after each build

### ISSUE THREAD

**Issue by neruthes** [neruthes/archiviation#2]
Very strangely, even if no change is made to the original cleartext files in `/source-articles`, the compiled ciphertext files in `/html/db` will always change every time I run `archiviation build`, and these files will hence be automatically staged when `git add .` is run, turning out that each commit will be unnecessarily large for containing unnecessary updates to articles whose cleartext counterparts actually remain unchanged.

In the source code:

```javascript
fs.writeFileSync('html/db/' + base32.encode(CryptoJS.SHA256(articleFileName_raw).toString()), CryptoJS.AES.encrypt(markdown.render(fs.readFileSync('source-articles/' + articleFileName_raw).toString()), keyForThisArticle).toString());
```
I don't see any chance can the ciphertext change.

I appreciate any assistance in fixing this bug.

cc @biergaizi

**Comment by neruthes** [comment]
As a solution, I have updated the compilation strategy. From now on, each time the user builds, the SHA256 hashes of the cleartext files will be cached. And only when a file's hash doesn't match its hash in the previous build will Archiviation write new ciphertext into `/html/db`.

But in the long run I'd better fix this problem once and for all.

**Comment by biergaizi** [comment]
I'll be free since 27th, and I can work full-time on this project, hopefully.
